(dp1
S'output'
p2
S"<type 'exceptions.ValueError'> invalid literal for long() with base 10: 'xdoimgJbNNW9qoa51633090332632010654.png'"
p3
sS'layer'
p4
S'/Users/andrewguterres/Desktop/web2py/applications/EZProject/controllers/default.py'
p5
sS'code'
p6
S'<code object <module> at 0x10f37a7b0, file "/Users/andrewguterres/Desktop/web2py/applications/EZProject/controllers/default.py", line 3>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/Users/andrewguterres/Desktop/web2py/gluon/restricted.py", line 219, in restricted\n    exec(ccode, environment)\n  File "/Users/andrewguterres/Desktop/web2py/applications/EZProject/controllers/default.py", line 49, in <module>\n  File "/Users/andrewguterres/Desktop/web2py/gluon/globals.py", line 419, in <lambda>\n    self._caller = lambda f: f()\n  File "/Users/andrewguterres/Desktop/web2py/applications/EZProject/controllers/default.py", line 22, in profile\n    user = db(myquery).select().first()\n  File "/Users/andrewguterres/Desktop/web2py/gluon/packages/dal/pydal/objects.py", line 2250, in select\n    return adapter.select(self.query, fields, attributes)\n  File "/Users/andrewguterres/Desktop/web2py/gluon/packages/dal/pydal/adapters/sqlite.py", line 82, in select\n    return super(SQLite, self).select(query, fields, attributes)\n  File "/Users/andrewguterres/Desktop/web2py/gluon/packages/dal/pydal/adapters/base.py", line 757, in select\n    colnames, sql = self._select_wcols(query, fields, **attributes)\n  File "/Users/andrewguterres/Desktop/web2py/gluon/packages/dal/pydal/adapters/base.py", line 672, in _select_wcols\n    query = self.expand(query, query_env=query_env)\n  File "/Users/andrewguterres/Desktop/web2py/gluon/packages/dal/pydal/adapters/base.py", line 434, in _expand\n    rv = op(first, second, **optional_args)\n  File "/Users/andrewguterres/Desktop/web2py/gluon/packages/dal/pydal/dialects/base.py", line 344, in eq\n    self.expand(second, first.type, query_env=query_env))\n  File "/Users/andrewguterres/Desktop/web2py/gluon/packages/dal/pydal/dialects/__init__.py", line 96, in expand\n    return self.adapter.expand(*args, **kwargs)\n  File "/Users/andrewguterres/Desktop/web2py/gluon/packages/dal/pydal/adapters/base.py", line 444, in _expand\n    rv = self.represent(expression, field_type)\n  File "/Users/andrewguterres/Desktop/web2py/gluon/packages/dal/pydal/adapters/base.py", line 381, in represent\n    return super(SQLAdapter, self).represent(obj, field_type)\n  File "/Users/andrewguterres/Desktop/web2py/gluon/packages/dal/pydal/adapters/base.py", line 335, in represent\n    return self.representer.represent(obj, field_type)\n  File "/Users/andrewguterres/Desktop/web2py/gluon/packages/dal/pydal/representers/__init__.py", line 251, in represent\n    rv = self.get_representer_for_type(field_type)(rv, field_type)\n  File "/Users/andrewguterres/Desktop/web2py/gluon/packages/dal/pydal/representers/__init__.py", line 139, in __call__\n    return self.adapt(self.call(value, field_type))\n  File "/Users/andrewguterres/Desktop/web2py/gluon/packages/dal/pydal/representers/__init__.py", line 136, in _call\n    return self.inner_call(value)\n  File "/Users/andrewguterres/Desktop/web2py/gluon/packages/dal/pydal/representers/__init__.py", line 124, in _inner_call\n    return self.obj.f(self.representer, value, **kwargs)\n  File "/Users/andrewguterres/Desktop/web2py/gluon/packages/dal/pydal/representers/base.py", line 26, in _id\n    return str(long(value))\nValueError: invalid literal for long() with base 10: \'xdoimgJbNNW9qoa51633090332632010654.png\'\n'
p11
s.